language: 
    python
python:
    - "3.7"
install:
    - pipenv install
    - pipenv shell
script: nosetests --with-coverage --cover-package=toqito
notifications:
    email: false
after_success:
    coveralls
