language: 
    python
python:
    - "3.7"
install:
    - sudo apt-get install libblas-dev liblapack-dev
    - pip install poetry
    - poetry install
    - poetry config virtualenvs.in-project true
    - source $(poetry env info --path)/bin/activate
script:
    - nosetests --with-coverage --cover-erase --cover-package=toqito
    - pylint tests/
notifications:
    email: false
after_success:
    coveralls
