language: 
    python
python:
    - "3.7"
install:
    - sudo apt-get install libblas-dev liblapack-dev
    - pip install poetry
    - poetry install
    - poetry config virtualenvs.in-project true
    - source $(poetry env info --path)/bin/activate
script:
    - nosetests --with-coverage --cover-erase --cover-package=toqito
    - pylint tests/
    - pylint toqito/
    - pydocstyle tests/
    - pydocstyle toqito/
notifications:
  email:
    recipients:
      - vincentrusso1@gmail.com
    on_success: always
    on_failure: always
after_success:
    coveralls
